version: '2'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - dhparam:/etc/nginx/dhparam
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
#    network_mode: bridge

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - certs:/etc/nginx/certs:rw
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=pgrishutenko@gmail.com
    network_mode: bridge

  whoami:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami.pavelgp.ml
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami.pavelgp.ml
      - LETSENCRYPT_EMAIL=pgrishutenko@gmail.com
  whoami2:
    image: jwilder/whoami
    expose:
      - "8000"
    environment:
      - VIRTUAL_HOST=whoami2.pavelgp.ml
      - VIRTUAL_PORT=8000
      - LETSENCRYPT_HOST=whoami2.pavelgp.ml
      - LETSENCRYPT_EMAIL=pgrishutenko@gmail.com

volumes:
  conf:
  vhost:
  html:
  dhparam:
  certs:
  acme: