version: '3'
services: 
    app1:
        image: "node:12-alpine"
        working_dir: /home/node/app
        volumes: 
            - .:/home/node/app
        environment: 
            - NODE_ENV=prodaction
            - PORT=5432
        ports: 
            - 8080:5432
        command: "npm start"
    
    app2:
        image: "node:12-alpine"
        working_dir: /home/node/app
        volumes: 
            - .:/home/node/app
        environment: 
            - NODE_ENV=debug
            - PORT=7732
        ports: 
            - 8000:7732
        command: "npm start"
